// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package captcha

import (
	"scaffold/internal/captcha/adapters"
	"scaffold/internal/captcha/handler"
	"scaffold/internal/captcha/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) func() {
	captchaCache := adapters.NewRedisCache()
	captchaServiceFactor := service.NewCaptchaServiceFactor(captchaCache)
	httpHandler := handler.NewHttpHandler(captchaServiceFactor)
	v := RegisterV1(r, httpHandler)
	return v
}

func NewVerifyMiddleware() *handler.HttpHandler {
	captchaCache := adapters.NewRedisCache()
	captchaServiceFactor := service.NewCaptchaServiceFactor(captchaCache)
	httpHandler := handler.NewHttpHandler(captchaServiceFactor)
	return httpHandler
}
