// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package role

import (
	"github.com/gin-gonic/gin"
	"scaffold/internal/role/adapters"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) bool {
	psqlRepository := adapters.NewPSQLRepository()
	redisCache := adapters.NewRedisCache()
	roleService := NewService(psqlRepository, redisCache)
	controller := NewController(roleService)
	bool2 := RegisterV1(r, controller)
	return bool2
}
