// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admin

import (
	"github.com/gin-gonic/gin"
	"scaffold/internal/domain/admin/controller"
	"scaffold/internal/domain/admin/infrastructure/cache"
	"scaffold/internal/domain/admin/infrastructure/db"
	"scaffold/internal/domain/admin/router"
	"scaffold/internal/domain/admin/service"
	"scaffold/internal/domain/admin/worker"
	"scaffold/pkg/repository"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) error {
	gormDB := repository.GormDB()
	dbDB := db.NewDB(gormDB)
	client := repository.RedisClient()
	cacheCache := cache.NewCache(client)
	serviceService := service.NewService(dbDB, cacheCache)
	controllerController := controller.NewController(serviceService)
	error2 := router.RegisterV1(r, controllerController)
	return error2
}

// wire.go:

func InitWorker() worker.Worker {
	gormDB := repository.GormDB()
	dbDB := db.NewDB(gormDB)
	client := repository.RedisClient()
	cacheCache := cache.NewCache(client)
	workerWorker := worker.NewWorker(dbDB, cacheCache)
	return workerWorker
}
