basePath: /api
definitions:
  domain.VerifyWay:
    enum:
    - image:click
    type: string
    x-enum-varnames:
    - WayImageClick
  handler.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/handler.UserResponse'
    type: object
  handler.CaptchaAnswerResponse:
    properties:
      audio:
        description: 音频验证码
        type: string
      id:
        example: "0"
        type: string
      image:
        description: 主图片
        type: string
      thumb:
        description: 缩略图
        type: string
      value:
        type: string
      way:
        $ref: '#/definitions/domain.VerifyWay'
    type: object
  handler.CaptchaResponse:
    properties:
      audio:
        description: 音频验证码
        type: string
      id:
        example: "0"
        type: string
      image:
        description: 主图片
        type: string
      thumb:
        description: 缩略图
        type: string
    type: object
  handler.GithubAuthRequest:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  handler.RefreshTokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handler.UserResponse:
    properties:
      avatar_url:
        type: string
      created_at:
        type: integer
      email:
        type: string
      email_verified:
        type: boolean
      id:
        type: integer
      last_login_at:
        type: integer
      updated_at:
        type: integer
      username:
        type: string
    type: object
  response.errorResponse:
    properties:
      code:
        type: integer
      details:
        additionalProperties: true
        type: object
      message:
        example: Internal server error
        type: string
    type: object
  response.invalidParamsResponse:
    properties:
      code:
        type: integer
      details:
        additionalProperties: true
        type: object
      message:
        example: invalid params
        type: string
    type: object
  response.successResponse:
    properties:
      code:
        example: 2000
        type: integer
      data: {}
      message:
        example: 请求成功
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: lirous@lirous.com
    name: Lirous
    url: https://Lirous.com
  description: 自定义描述
  license:
    name: MIT
    url: https://github.com/Lirous587/go-scaffold/main/LICENSE
  termsOfService: https://Lirous.com
  title: 自定义title
  version: "1.0"
paths:
  /v1/captcha:
    post:
      consumes:
      - application/json
      parameters:
      - enum:
        - image:click
        in: query
        name: way
        type: string
        x-enum-varnames:
        - WayImageClick
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/response.successResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.CaptchaResponse'
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.invalidParamsResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/response.errorResponse'
      summary: 生成验证码
      tags:
      - captcha
  /v1/captcha/with-answer:
    get:
      consumes:
      - application/json
      description: 创建新的验证码并返回答案（仅用于测试或开发环境）
      parameters:
      - enum:
        - image:click
        in: query
        name: way
        type: string
        x-enum-varnames:
        - WayImageClick
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/response.successResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.CaptchaAnswerResponse'
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.invalidParamsResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/response.errorResponse'
      summary: 生成带答案的验证码
      tags:
      - captcha
  /v1/user/auth:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/response.successResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: 校验令牌
      tags:
      - user
  /v1/user/auth/github:
    post:
      consumes:
      - application/json
      description: 使用 GitHub OAuth 登录，返回用户信息和令牌
      parameters:
      - description: GitHub 授权码
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.GithubAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/response.successResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.AuthResponse'
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.invalidParamsResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/response.errorResponse'
      summary: GitHub 授权登录
      tags:
      - user
  /v1/user/profile:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.successResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.UserResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: 获取用户信息
      tags:
      - user
  /v1/user/refresh_token:
    post:
      consumes:
      - application/json
      description: 使用刷新令牌获取新的访问令牌
      parameters:
      - description: refresh_token刷新令牌
        in: header
        name: X-Refresh-Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/response.successResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.RefreshTokenResponse'
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.errorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/response.errorResponse'
      summary: 刷新令牌
      tags:
      - user
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
