// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middleware

import (
	"scaffold/pkg/config"
)

// Injectors from wire.go:

// InitializeAdminAPI 初始化Admin模块的API
func InitAdminAuth() (Auth, error) {
	v := provideJWTSecret()
	auth := NewAdminAuth(v)
	return auth, nil
}

// wire.go:

// provideJWTSecret 提供JWT Secret
func provideJWTSecret() []byte {
	return []byte(config.Cfg.JWT.Secret)
}
