// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package moment

import (
	"blog-v4/internal/moment/adapters"
	"blog-v4/internal/moment/handler"
	"blog-v4/internal/moment/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) func() {
	momentRepository := adapters.NewPSQLMomentRepository()
	momentService := service.NewMomentService(momentRepository)
	httpHandler := handler.NewHttpHandler(momentService)
	v := RegisterV1(r, httpHandler)
	return v
}
