// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/gin-gonic/gin"
	"scaffold/internal/domain/user/infrastructure"
	"scaffold/pkg/repository"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) error {
	db := repository.GormDB()
	idb := infrastructure.NewDB(db)
	client := repository.RedisClient()
	iCache := infrastructure.NewCache(client)
	iService := NewService(idb, iCache)
	iController := NewController(iService)
	error2 := RegisterV1(r, iController)
	return error2
}
