// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package img

import (
	"scaffold/internal/img/adapters"
	"scaffold/internal/img/handler"
	"scaffold/internal/img/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) func() {
	imgRepository := adapters.NewPSQLImgRepository()
	imgMsgQueue := adapters.NewImgRedisCache()
	imgService := service.NewImgService(imgRepository, imgMsgQueue)
	httpHandler := handler.NewHttpHandler(imgService)
	v := RegisterV1(r, httpHandler)
	return v
}
