// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Articles       string
	ArticlesLabels string
	Friendlinks    string
	Img            string
	ImgCategory    string
	Labels         string
	Maxims         string
	Moments        string
	Users          string
}{
	Articles:       "articles",
	ArticlesLabels: "articles_labels",
	Friendlinks:    "friendlinks",
	Img:            "img",
	ImgCategory:    "img_category",
	Labels:         "labels",
	Maxims:         "maxims",
	Moments:        "moments",
	Users:          "users",
}
