// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	OrganizationMembers string
	Organizations       string
	Plans               string
	ProjectMembers      string
	Projects            string
	UsageStats          string
	Users               string
}{
	OrganizationMembers: "organization_members",
	Organizations:       "organizations",
	Plans:               "plans",
	ProjectMembers:      "project_members",
	Projects:            "projects",
	UsageStats:          "usage_stats",
	Users:               "users",
}
