// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	ImgCategories string
	Imgs          string
	Mock          string
	Users         string
}{
	ImgCategories: "img_categories",
	Imgs:          "imgs",
	Mock:          "mock",
	Users:         "users",
}
