// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// OrganizationMember is an object representing the database table.
type OrganizationMember struct {
	OrgID    string      `boil:"org_id" json:"org_id" toml:"org_id" yaml:"org_id"`
	UserID   string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Role     string      `boil:"role" json:"role" toml:"role" yaml:"role"`
	JoinedAt null.Time   `boil:"joined_at" json:"joined_at,omitempty" toml:"joined_at" yaml:"joined_at,omitempty"`
	Status   null.String `boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`

	R *organizationMemberR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L organizationMemberL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OrganizationMemberColumns = struct {
	OrgID    string
	UserID   string
	Role     string
	JoinedAt string
	Status   string
}{
	OrgID:    "org_id",
	UserID:   "user_id",
	Role:     "role",
	JoinedAt: "joined_at",
	Status:   "status",
}

var OrganizationMemberTableColumns = struct {
	OrgID    string
	UserID   string
	Role     string
	JoinedAt string
	Status   string
}{
	OrgID:    "organization_members.org_id",
	UserID:   "organization_members.user_id",
	Role:     "organization_members.role",
	JoinedAt: "organization_members.joined_at",
	Status:   "organization_members.status",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var OrganizationMemberWhere = struct {
	OrgID    whereHelperstring
	UserID   whereHelperstring
	Role     whereHelperstring
	JoinedAt whereHelpernull_Time
	Status   whereHelpernull_String
}{
	OrgID:    whereHelperstring{field: "\"organization_members\".\"org_id\""},
	UserID:   whereHelperstring{field: "\"organization_members\".\"user_id\""},
	Role:     whereHelperstring{field: "\"organization_members\".\"role\""},
	JoinedAt: whereHelpernull_Time{field: "\"organization_members\".\"joined_at\""},
	Status:   whereHelpernull_String{field: "\"organization_members\".\"status\""},
}

// OrganizationMemberRels is where relationship names are stored.
var OrganizationMemberRels = struct {
}{}

// organizationMemberR is where relationships are stored.
type organizationMemberR struct {
}

// NewStruct creates a new relationship struct
func (*organizationMemberR) NewStruct() *organizationMemberR {
	return &organizationMemberR{}
}

// organizationMemberL is where Load methods for each relationship are stored.
type organizationMemberL struct{}

var (
	organizationMemberAllColumns            = []string{"org_id", "user_id", "role", "joined_at", "status"}
	organizationMemberColumnsWithoutDefault = []string{"org_id", "user_id"}
	organizationMemberColumnsWithDefault    = []string{"role", "joined_at", "status"}
	organizationMemberPrimaryKeyColumns     = []string{"org_id", "user_id"}
	organizationMemberGeneratedColumns      = []string{}
)

type (
	// OrganizationMemberSlice is an alias for a slice of pointers to OrganizationMember.
	// This should almost always be used instead of []OrganizationMember.
	OrganizationMemberSlice []*OrganizationMember
	// OrganizationMemberHook is the signature for custom OrganizationMember hook methods
	OrganizationMemberHook func(context.Context, boil.ContextExecutor, *OrganizationMember) error

	organizationMemberQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	organizationMemberType                 = reflect.TypeOf(&OrganizationMember{})
	organizationMemberMapping              = queries.MakeStructMapping(organizationMemberType)
	organizationMemberPrimaryKeyMapping, _ = queries.BindMapping(organizationMemberType, organizationMemberMapping, organizationMemberPrimaryKeyColumns)
	organizationMemberInsertCacheMut       sync.RWMutex
	organizationMemberInsertCache          = make(map[string]insertCache)
	organizationMemberUpdateCacheMut       sync.RWMutex
	organizationMemberUpdateCache          = make(map[string]updateCache)
	organizationMemberUpsertCacheMut       sync.RWMutex
	organizationMemberUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var organizationMemberAfterSelectMu sync.Mutex
var organizationMemberAfterSelectHooks []OrganizationMemberHook

var organizationMemberBeforeInsertMu sync.Mutex
var organizationMemberBeforeInsertHooks []OrganizationMemberHook
var organizationMemberAfterInsertMu sync.Mutex
var organizationMemberAfterInsertHooks []OrganizationMemberHook

var organizationMemberBeforeUpdateMu sync.Mutex
var organizationMemberBeforeUpdateHooks []OrganizationMemberHook
var organizationMemberAfterUpdateMu sync.Mutex
var organizationMemberAfterUpdateHooks []OrganizationMemberHook

var organizationMemberBeforeDeleteMu sync.Mutex
var organizationMemberBeforeDeleteHooks []OrganizationMemberHook
var organizationMemberAfterDeleteMu sync.Mutex
var organizationMemberAfterDeleteHooks []OrganizationMemberHook

var organizationMemberBeforeUpsertMu sync.Mutex
var organizationMemberBeforeUpsertHooks []OrganizationMemberHook
var organizationMemberAfterUpsertMu sync.Mutex
var organizationMemberAfterUpsertHooks []OrganizationMemberHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *OrganizationMember) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *OrganizationMember) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *OrganizationMember) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *OrganizationMember) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *OrganizationMember) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *OrganizationMember) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *OrganizationMember) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *OrganizationMember) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *OrganizationMember) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organizationMemberAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOrganizationMemberHook registers your hook function for all future operations.
func AddOrganizationMemberHook(hookPoint boil.HookPoint, organizationMemberHook OrganizationMemberHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		organizationMemberAfterSelectMu.Lock()
		organizationMemberAfterSelectHooks = append(organizationMemberAfterSelectHooks, organizationMemberHook)
		organizationMemberAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		organizationMemberBeforeInsertMu.Lock()
		organizationMemberBeforeInsertHooks = append(organizationMemberBeforeInsertHooks, organizationMemberHook)
		organizationMemberBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		organizationMemberAfterInsertMu.Lock()
		organizationMemberAfterInsertHooks = append(organizationMemberAfterInsertHooks, organizationMemberHook)
		organizationMemberAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		organizationMemberBeforeUpdateMu.Lock()
		organizationMemberBeforeUpdateHooks = append(organizationMemberBeforeUpdateHooks, organizationMemberHook)
		organizationMemberBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		organizationMemberAfterUpdateMu.Lock()
		organizationMemberAfterUpdateHooks = append(organizationMemberAfterUpdateHooks, organizationMemberHook)
		organizationMemberAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		organizationMemberBeforeDeleteMu.Lock()
		organizationMemberBeforeDeleteHooks = append(organizationMemberBeforeDeleteHooks, organizationMemberHook)
		organizationMemberBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		organizationMemberAfterDeleteMu.Lock()
		organizationMemberAfterDeleteHooks = append(organizationMemberAfterDeleteHooks, organizationMemberHook)
		organizationMemberAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		organizationMemberBeforeUpsertMu.Lock()
		organizationMemberBeforeUpsertHooks = append(organizationMemberBeforeUpsertHooks, organizationMemberHook)
		organizationMemberBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		organizationMemberAfterUpsertMu.Lock()
		organizationMemberAfterUpsertHooks = append(organizationMemberAfterUpsertHooks, organizationMemberHook)
		organizationMemberAfterUpsertMu.Unlock()
	}
}

// One returns a single organizationMember record from the query.
func (q organizationMemberQuery) One(ctx context.Context, exec boil.ContextExecutor) (*OrganizationMember, error) {
	o := &OrganizationMember{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: failed to execute a one query for organization_members")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all OrganizationMember records from the query.
func (q organizationMemberQuery) All(ctx context.Context, exec boil.ContextExecutor) (OrganizationMemberSlice, error) {
	var o []*OrganizationMember

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orm: failed to assign all query results to OrganizationMember slice")
	}

	if len(organizationMemberAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all OrganizationMember records in the query.
func (q organizationMemberQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to count organization_members rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q organizationMemberQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orm: failed to check if organization_members exists")
	}

	return count > 0, nil
}

// OrganizationMembers retrieves all the records using an executor.
func OrganizationMembers(mods ...qm.QueryMod) organizationMemberQuery {
	mods = append(mods, qm.From("\"organization_members\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"organization_members\".*"})
	}

	return organizationMemberQuery{q}
}

// FindOrganizationMember retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOrganizationMember(ctx context.Context, exec boil.ContextExecutor, orgID string, userID string, selectCols ...string) (*OrganizationMember, error) {
	organizationMemberObj := &OrganizationMember{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"organization_members\" where \"org_id\"=$1 AND \"user_id\"=$2", sel,
	)

	q := queries.Raw(query, orgID, userID)

	err := q.Bind(ctx, exec, organizationMemberObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: unable to select from organization_members")
	}

	if err = organizationMemberObj.doAfterSelectHooks(ctx, exec); err != nil {
		return organizationMemberObj, err
	}

	return organizationMemberObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *OrganizationMember) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no organization_members provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(organizationMemberColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	organizationMemberInsertCacheMut.RLock()
	cache, cached := organizationMemberInsertCache[key]
	organizationMemberInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			organizationMemberAllColumns,
			organizationMemberColumnsWithDefault,
			organizationMemberColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(organizationMemberType, organizationMemberMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(organizationMemberType, organizationMemberMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"organization_members\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"organization_members\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orm: unable to insert into organization_members")
	}

	if !cached {
		organizationMemberInsertCacheMut.Lock()
		organizationMemberInsertCache[key] = cache
		organizationMemberInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the OrganizationMember.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *OrganizationMember) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	organizationMemberUpdateCacheMut.RLock()
	cache, cached := organizationMemberUpdateCache[key]
	organizationMemberUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			organizationMemberAllColumns,
			organizationMemberPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("orm: unable to update organization_members, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"organization_members\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, organizationMemberPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(organizationMemberType, organizationMemberMapping, append(wl, organizationMemberPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update organization_members row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by update for organization_members")
	}

	if !cached {
		organizationMemberUpdateCacheMut.Lock()
		organizationMemberUpdateCache[key] = cache
		organizationMemberUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q organizationMemberQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all for organization_members")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected for organization_members")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OrganizationMemberSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organizationMemberPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"organization_members\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, organizationMemberPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all in organizationMember slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected all in update all organizationMember")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *OrganizationMember) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("orm: no organization_members provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(organizationMemberColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	organizationMemberUpsertCacheMut.RLock()
	cache, cached := organizationMemberUpsertCache[key]
	organizationMemberUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			organizationMemberAllColumns,
			organizationMemberColumnsWithDefault,
			organizationMemberColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			organizationMemberAllColumns,
			organizationMemberPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orm: unable to upsert organization_members, could not build update column list")
		}

		ret := strmangle.SetComplement(organizationMemberAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(organizationMemberPrimaryKeyColumns) == 0 {
				return errors.New("orm: unable to upsert organization_members, could not build conflict column list")
			}

			conflict = make([]string, len(organizationMemberPrimaryKeyColumns))
			copy(conflict, organizationMemberPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"organization_members\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(organizationMemberType, organizationMemberMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(organizationMemberType, organizationMemberMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orm: unable to upsert organization_members")
	}

	if !cached {
		organizationMemberUpsertCacheMut.Lock()
		organizationMemberUpsertCache[key] = cache
		organizationMemberUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single OrganizationMember record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *OrganizationMember) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("orm: no OrganizationMember provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), organizationMemberPrimaryKeyMapping)
	sql := "DELETE FROM \"organization_members\" WHERE \"org_id\"=$1 AND \"user_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete from organization_members")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by delete for organization_members")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q organizationMemberQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orm: no organizationMemberQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from organization_members")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for organization_members")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OrganizationMemberSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(organizationMemberBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organizationMemberPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"organization_members\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, organizationMemberPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from organizationMember slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for organization_members")
	}

	if len(organizationMemberAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *OrganizationMember) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOrganizationMember(ctx, exec, o.OrgID, o.UserID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OrganizationMemberSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OrganizationMemberSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organizationMemberPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"organization_members\".* FROM \"organization_members\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, organizationMemberPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orm: unable to reload all in OrganizationMemberSlice")
	}

	*o = slice

	return nil
}

// OrganizationMemberExists checks if the OrganizationMember row exists.
func OrganizationMemberExists(ctx context.Context, exec boil.ContextExecutor, orgID string, userID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"organization_members\" where \"org_id\"=$1 AND \"user_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, orgID, userID)
	}
	row := exec.QueryRowContext(ctx, sql, orgID, userID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orm: unable to check if organization_members exists")
	}

	return exists, nil
}

// Exists checks if the OrganizationMember row exists.
func (o *OrganizationMember) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OrganizationMemberExists(ctx, exec, o.OrgID, o.UserID)
}
