// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mock


import (
	"github.com/gin-gonic/gin"
	"scaffold/internal/mock/adapters"
	"scaffold/internal/mock/handler"
	"scaffold/internal/mock/service"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) func() {
	mockRepository := adapters.NewPSQLMockRepository()
	mockService := service.NewMockService(mockRepository)
	httpHandler := handler.NewHttpHandler(mockService)
	v := RegisterV1(r, httpHandler)
	return v
}
